name: Check

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            name: macOS (arm64)

          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: Ubuntu Musl (x86-64)

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: Windows MSVC (x86-64)

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          key: check-${{ matrix.os }}-${{ matrix.target }}

      - name: Installing macOS dependencies
        if: contains(matrix.os, 'macos-')
        run: |
          brew install openssl make

      - name: Installing Windows dependencies
        if: contains(matrix.os, 'windows-')
        run: choco install make -y
        shell: pwsh

      - name: Installing Linux dependencies for musl
        if: contains(matrix.os, 'ubuntu-') && contains(matrix.target, '-musl')
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq musl-dev musl-tools

      - name: Lint
        run: make fmt TARGET=${{ matrix.target }}

      - name: Test
        run: make test TARGET=${{ matrix.target }} EXE=pcrypt-${{ matrix.os }}-${{ matrix.target }}

      - name: Build
        run: make release TARGET=${{ matrix.target }} EXE=pcrypt-${{ matrix.os }}-${{ matrix.target }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pcrypt-${{ matrix.os }}-${{ matrix.target }}
          path: build/pcrypt-*
          retention-days: 10
